/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : CRC1.c
**     Project     : piproject
**     Processor   : MKE06Z128VLD4
**     Component   : CRC_LDD
**     Version     : Component 01.014, Driver 01.07, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2017-10-15, 00:13, # CodeGen: 2
**     Abstract    :
**         This component implements the Cyclic Redundancy Check (CRC) code calculation.
**     Settings    :
**          Component name                                 : CRC1
**          Device                                         : CRC
**          Settings                                       : 
**            CRC standard                                 : CRC16
**          Initialization                                 : 
**            Auto initialization                          : yes
**     Contents    :
**         Init         - LDD_TDeviceData* CRC1_Init(LDD_TUserData *UserDataPtr);
**         GetCRCResult - uint32_t CRC1_GetCRCResult(LDD_TDeviceData *DeviceDataPtr);
**         GetCRC8      - uint32_t CRC1_GetCRC8(LDD_TDeviceData *DeviceDataPtr, uint8_t Data);
**         GetCRC16     - uint32_t CRC1_GetCRC16(LDD_TDeviceData *DeviceDataPtr, uint16_t Data);
**         GetBlockCRC  - LDD_TError CRC1_GetBlockCRC(LDD_TDeviceData *DeviceDataPtr, LDD_TData* Ptr,...
**         ResetCRC     - void CRC1_ResetCRC(LDD_TDeviceData *DeviceDataPtr);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file CRC1.c
** @version 01.07
** @brief
**         This component implements the Cyclic Redundancy Check (CRC) code calculation.
*/         
/*!
**  @addtogroup CRC1_module CRC1 module documentation
**  @{
*/         

/* MODULE CRC1. */

/* MQX Lite include files */
#include "mqxlite.h"
#include "mqxlite_prv.h"
#include "CRC1.h"

#ifdef __cplusplus
extern "C" {
#endif 

/* {MQXLite RTOS Adapter} Static object used for simulation of dynamic driver memory allocation */
static CRC1_TDeviceData DeviceDataPtr__DEFAULT_RTOS_ALLOC;

/*
** ===================================================================
**     Method      :  CRC1_Init (component CRC_LDD)
*/
/*!
**     @brief
**         Initializes the device and allocates memory for the private
**         device data structure.
**     @param
**         UserDataPtr     - Pointer to the user or
**                           RTOS specific data. This pointer will be
**                           passed as an event or callback parameter.
**     @return
**                         - Pointer to the dynamically allocated private
**                           structure or NULL if there was an error.
*/
/* ===================================================================*/
LDD_TDeviceData* CRC1_Init(LDD_TUserData *UserDataPtr)
{
  CRC1_TDeviceDataPtr DeviceDataPtr;

  /* Allocate LDD device structure */
  /* {MQXLite RTOS Adapter} Driver memory allocation: Dynamic allocation is simulated by a pointer to the static object */
  DeviceDataPtr = &DeviceDataPtr__DEFAULT_RTOS_ALLOC;
  DeviceDataPtr->UserDataPtr = UserDataPtr; /* Store the RTOS device structure */
  /* SIM_SCGC: CRC=1 */
  SIM_SCGC |= SIM_SCGC_CRC_MASK;
  DeviceDataPtr->CRCStandard = LDD_CRC_16;
  DeviceDataPtr->SeedLow = 0x00U;
  /* CRC_CTRL: TOT=1,TOTR=2,??=0,FXOR=0,WAS=1,TCRC=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  CRC_CTRL = (CRC_CTRL_TOT(0x01) | CRC_CTRL_TOTR(0x02) | CRC_CTRL_WAS_MASK); /* Setup CRC16 mode */
  /* CRC_DATA: LU=0,LL=0 */
  CRC_DATA &= (uint32_t)~(uint32_t)((CRC_DATA_LU(0xFF) | CRC_DATA_LL(0xFF))); /* Setup seed */
  /* CRC_GPOLY: LOW=0x8005 */
  CRC_GPOLY = (uint32_t)((CRC_GPOLY & (uint32_t)~(uint32_t)(
               CRC_GPOLY_LOW(0x7FFA)
              )) | (uint32_t)(
               CRC_GPOLY_LOW(0x8005)
              ));                      /* Setup polynomial */
  /* CRC_CTRL: WAS=0 */
  CRC_CTRL &= (uint32_t)~(uint32_t)(CRC_CTRL_WAS_MASK); /* Clear seed bit */
  /* Registration of the device structure */
  PE_LDD_RegisterDeviceStructure(PE_LDD_COMPONENT_CRC1_ID,DeviceDataPtr);
  return ((LDD_TDeviceData *)DeviceDataPtr);
}

/*
** ===================================================================
**     Method      :  CRC1_ResetCRC (component CRC_LDD)
*/
/*!
**     @brief
**         Reset CRC module for new CRC computation. This method keeps
**         previous settings (CRC standard, seed value...).
**     @param
**         DeviceDataPtr   - Pointer to the user or
**                           RTOS specific data. This pointer will be
**                           passed as an event or callback parameter.
*/
/* ===================================================================*/
void CRC1_ResetCRC(LDD_TDeviceData *DeviceDataPtr)
{
  CRC1_TDeviceData *DeviceDataPrv = (CRC1_TDeviceData*)DeviceDataPtr;

  CRC_PDD_SetSeedBit(CRC_BASE_PTR); /* set seed mode */
  if (DeviceDataPrv->CRC32bit == TRUE) { /* 32bit CRC? */
    CRC_PDD_SetSeedHigh(CRC_BASE_PTR, DeviceDataPrv->SeedHigh); /* setup seed high */
  }
  CRC_PDD_SetSeedLow(CRC_BASE_PTR, DeviceDataPrv->SeedLow); /* setup seed low */
  CRC_PDD_ClearSeedBit(CRC_BASE_PTR); /* clear seed mode */
}

/*
** ===================================================================
**     Method      :  CRC1_GetCRC8 (component CRC_LDD)
*/
/*!
**     @brief
**         This method appends 1 data byte to current CRC calculation
**         and returns new result. It automatically enables code
**         generation of GetCRCResult method.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by Init method. 
**     @param
**         Data            - New data value for actual CRC
**                           computation.
**     @return
**                         - Returns current CRC result. 
*/
/* ===================================================================*/
uint32_t CRC1_GetCRC8(LDD_TDeviceData *DeviceDataPtr, uint8_t Data)
{
  uint32_t result;
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */

  CRC_PDD_SetCRCDataLLRegister(CRC_BASE_PTR, Data); /* 8bit access */
  result = CRC1_GetCRCResult(DeviceDataPtr);
  return result;
}

/*
** ===================================================================
**     Method      :  CRC1_GetBlockCRC (component CRC_LDD)
*/
/*!
**     @brief
**         Gets CRC of data block. This method receives a pointer to a
**         memory location and calculates the CRC of the whole memory
**         block. It automatically enables code generation of
**         GetCRCResult method.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by Init method. 
**     @param
**         Ptr             - Pointer to data block in memory which will
**                           be CRC checksummed.
**     @param
**         Length          - Length of buffer in bytes.
**     @param
**         Result          - Pointer to variable where the result
**                           will be stored. 
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_RANGE - NULL pointer passed or length
**                           is 0.
*/
/* ===================================================================*/
LDD_TError CRC1_GetBlockCRC(LDD_TDeviceData *DeviceDataPtr, LDD_TData* Ptr, uint32_t Length, uint32_t *Result)
{
  void *tmpPtr;
  uint32_t *tmpPtr2 = (uint32_t *)Ptr;
  uint8_t oldInputTranspose;
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */

  if ((Ptr == NULL) || (Length == 0x00U)) { /* Is the input buffer prepared? */
    return ERR_RANGE;                  /* If no then error */
  }
	 /* flip bytes because of little endian architecture */
	 oldInputTranspose = CRC_PDD_GetInputTranspose(CRC_BASE_PTR);
	 switch (oldInputTranspose) {
	   case CRC_PDD_NO_TRANSPOSE:
	     CRC_PDD_SetInputTranspose(CRC_BASE_PTR, CRC_PDD_BYTES);
	     break;
	   case CRC_PDD_BITS:
	     CRC_PDD_SetInputTranspose(CRC_BASE_PTR, CRC_PDD_BITS_AND_BYTES);
	     break;
	   case CRC_PDD_BITS_AND_BYTES:
	     CRC_PDD_SetInputTranspose(CRC_BASE_PTR, CRC_PDD_BITS);
	     break;
	   case CRC_PDD_BYTES:
	     CRC_PDD_SetInputTranspose(CRC_BASE_PTR, CRC_PDD_NO_TRANSPOSE);
	     break;
	   default:
	     break;
	 }
  /* Start the checksum calculation */
  while (Length >= 0x04U) {
    CRC_PDD_SetCRCDataRegister(CRC_BASE_PTR,*(tmpPtr2++)); /* 32bit access */
    Length -= 0x04U;
  }
  tmpPtr = (void*)tmpPtr2;
  switch (Length) {
    case 0x03U:
      CRC_PDD_SetCRCDataLRegister(CRC_BASE_PTR,*(uint16_t*)tmpPtr); /* 16bit access */
      CRC_PDD_SetCRCDataLLRegister(CRC_BASE_PTR,*((uint8_t*)tmpPtr+0x02U)); /* 8bit access */
      break;
    case 0x02U:
      CRC_PDD_SetCRCDataLRegister(CRC_BASE_PTR,*(uint16_t*)tmpPtr); /* 16bit access */
      break;
    case 0x01U:
      CRC_PDD_SetCRCDataLLRegister(CRC_BASE_PTR,*(uint8_t*)tmpPtr); /* 8bit access */
      break;
    default:
      break;
  }
  *Result = CRC1_GetCRCResult(DeviceDataPtr);
  CRC_PDD_SetInputTranspose(CRC_BASE_PTR, oldInputTranspose); /* revert byte flipping */
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  CRC1_GetCRCResult (component CRC_LDD)
*/
/*!
**     @brief
**         Returns actual CRC result. This method cannot be disabled if
**         at least one of the following methods is enabled: GetCRC8,
**         GetCRC16, GetCRC32, GetBlockCRC.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by Init method. 
**     @return
**                         - Returns current CRC result. 
*/
/* ===================================================================*/
uint32_t CRC1_GetCRCResult(LDD_TDeviceData *DeviceDataPtr)
{
  uint32_t result;
  CRC1_TDeviceData *DeviceDataPrv = (CRC1_TDeviceData*)DeviceDataPtr;
  uint8_t transpose;
  
  transpose = (uint8_t)CRC_PDD_GetOutputTranspose(CRC_BASE_PTR);
  if (DeviceDataPrv->CRC32bit == FALSE) {
    if ((transpose == (uint8_t)CRC_PDD_BITS_AND_BYTES) || (transpose == (uint8_t)CRC_PDD_BYTES)) {
      result = CRC_PDD_GetCRCDataHRegister(CRC_BASE_PTR); /* Return upper 16bits of CRC because of transposition in 16bit mode */
    } else {
      result = CRC_PDD_GetCRCDataLRegister(CRC_BASE_PTR); /* Return lower 16bits of CRC */
    }
    return result;
  }
  result = CRC_PDD_GetCRCDataRegister(CRC_BASE_PTR); /* Return 32bit CRC */
  return result;
}

/*
** ===================================================================
**     Method      :  CRC1_GetCRC16 (component CRC_LDD)
*/
/*!
**     @brief
**         This method appends 2 data bytes to current CRC calculation
**         and returns new result. It automatically enables code
**         generation of GetCRCResult method.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by Init method. 
**     @param
**         Data            - New data value for actual CRC
**                           computation.
**     @return
**                         - Returns current CRC result. 
*/
/* ===================================================================*/
uint32_t CRC1_GetCRC16(LDD_TDeviceData *DeviceDataPtr, uint16_t Data)
{
  uint32_t result;

  CRC_PDD_SetCRCDataLRegister(CRC_BASE_PTR, Data); /* 16bit access */
  result = CRC1_GetCRCResult(DeviceDataPtr);
  return result;
}

/* END CRC1. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
