/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : flash.c
**     Project     : piproject
**     Processor   : MKE06Z128VLD4
**     Component   : IntFLASH
**     Version     : Component 02.409, Driver 01.02, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2017-10-15, 00:13, # CodeGen: 2
**     Abstract    :
**         This component "IntFLASH" implements an access to internal FLASH.
**         The component support reading/writing data into FLASH, erasing of
**         selected sector.
**         The component supports events if the write interrupt is supported.
**         The component supports following modes of write operations:
**           - Write - writing without any test.
**           - Destructive write - sector is erased if necessary.
**           - Safe write - user event is invoked to save and resore data
**                          from the current sector.
**         The component requires on-chip FLASH memory (not used/allocated by
**         other components).
**     Settings    :
**          Component name                                 : flash
**          FLASH                                          : FTMRE
**          FLASH_LDD                                      : FLASH_LDD
**          Write method                                   : Destructive write (with erase)
**          Interrupt service/event                        : Enabled
**            Command complete interrupt                   : 
**              Interrupt                                  : INT_FTMRE
**              Interrupt priority                         : medium priority
**          Wait in RAM                                    : yes
**          Virtual page                                   : Disabled
**          Initialization                                 : 
**            Events enabled in init.                      : yes
**            Wait enabled in init.                        : yes
**          CPU clock/speed selection                      : 
**            FLASH clock                                  : 
**            High speed mode                              : This component enabled
**            Low speed mode                               : This component disabled
**            Slow speed mode                              : This component disabled
**     Contents    :
**         DisableEvent  - byte flash_DisableEvent(void);
**         EnableEvent   - byte flash_EnableEvent(void);
**         Busy          - bool flash_Busy(byte Block);
**         EraseSector   - byte flash_EraseSector(flash_TAddress Addr);
**         SetByteFlash  - byte flash_SetByteFlash(flash_TAddress Addr, byte Data);
**         SetWordFlash  - byte flash_SetWordFlash(flash_TAddress Addr, word Data);
**         SetBlockFlash - byte flash_SetBlockFlash(flash_TDataAddress Source, flash_TAddress Dest, word...
**         GetBlockFlash - byte flash_GetBlockFlash(flash_TAddress Source, flash_TDataAddress Dest, word...
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file flash.c
** @version 01.02
** @brief
**         This component "IntFLASH" implements an access to internal FLASH.
**         The component support reading/writing data into FLASH, erasing of
**         selected sector.
**         The component supports events if the write interrupt is supported.
**         The component supports following modes of write operations:
**           - Write - writing without any test.
**           - Destructive write - sector is erased if necessary.
**           - Safe write - user event is invoked to save and resore data
**                          from the current sector.
**         The component requires on-chip FLASH memory (not used/allocated by
**         other components).
*/         
/*!
**  @addtogroup flash_module flash module documentation
**  @{
*/         

/* MODULE flash. */

#include "Events.h"
#include "flash.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Internal method prototypes */

#define flash_TOTAL_FLASH_BLOCK_COUNT  0x01U
#define flash_P_FLASH_SIZE             0x00020000U
#define flash_P_FLASH_BLOCK_COUNT      0x01U
#define flash_P_FLASH_BLOCK_SIZE       0x00020000U

#define flash_CMD_NONE                 0x00U
#define flash_CMD_READ                 0x01U
#define flash_CMD_ERASE_SECTOR         0x02U
#define flash_CMD_ERASE_BLOCK          0x03U
#define flash_CMD_VERIFY_ERASED_BLOCK  0x04U
#define flash_CMD_WRITE                0x05U
#define flash_CMD_WRITE_ERASE          0x06U

typedef struct flash_TSector_Struct {
  uint32_t Data[IntFlashLdd1_FLASH_ERASABLE_UNIT_SIZE/4U];
} flash_TSector;

static uint32_t flash_CurrentCommand;  /* Current command */
static bool flash_CmdResult;           /* Last command result */
static bool flash_CmdPending;          /* Current command state */
static bool flash_EnEvent;             /* State of events (enabled/disabled) */

static LDD_TDeviceData* IntFlashLdd1_DevDataPtr;
static LDD_TData *flash_DataAddress;
static LDD_FLASH_TAddress flash_FlashAddress;
static LDD_FLASH_TDataSize flash_DataSize;

byte flash_SetFlash(flash_TDataAddress Source, flash_TAddress Dest, word Count);

/*
** ===================================================================
**     Method      :  flash_SetFlash (component IntFLASH)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
byte flash_SetFlash(flash_TDataAddress Src, flash_TAddress Dst, word Count)
{
  LDD_TError                 Result;
  uint32_t                   x;

  if (flash_CmdPending) {
    return ERR_BUSY;
  }
  for (x=0U; x<Count; x++) {           /* Check if written area is erased */
    if (((uint8_t*)Dst)[x] != 0xFFU) { /* Byte erased? */
      flash_CurrentCommand = flash_CMD_WRITE_ERASE;
      flash_CmdPending = TRUE;
      flash_DataAddress = (LDD_TData *)Src;
      flash_FlashAddress = Dst;
      flash_DataSize = Count;
      Result = IntFlashLdd1_Erase(IntFlashLdd1_DevDataPtr, (LDD_FLASH_TAddress)(Dst & ~(LDD_FLASH_TAddress)IntFlashLdd1_FLASH_ERASABLE_UNIT_MASK), IntFlashLdd1_FLASH_ERASABLE_UNIT_SIZE);
      if (Result == ERR_OK) {
        do {
        } while (flash_CmdPending);
        Result = flash_CmdResult;
      } else {
        flash_CmdPending = FALSE;      /* Command parameter error */
        if (Result == ERR_PARAM_ADDRESS) {
          Result = ERR_RANGE;
        }
      }
      return (byte)Result;
    }
  }
  flash_CurrentCommand = flash_CMD_WRITE;
  flash_CmdPending = TRUE;
  Result = IntFlashLdd1_Write(IntFlashLdd1_DevDataPtr, (LDD_TData *)Src, Dst, (LDD_FLASH_TDataSize)Count); /* Start reading from the flash memory */
  if (Result == ERR_OK) {
    do {
    } while (flash_CmdPending);
    Result = flash_CmdResult;
  } else {
    flash_CmdPending = FALSE;          /* Command parameter error */
    if (Result == ERR_PARAM_ADDRESS) {
      Result = ERR_RANGE;
    }
  }
  return (byte)Result;
}

/*
** ===================================================================
**     Method      :  flash_Init (component IntFLASH)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void flash_Init(void)
{
  IntFlashLdd1_DevDataPtr = IntFlashLdd1_Init(NULL);
  flash_CmdPending = FALSE;
  flash_EnEvent = TRUE;                /* Remember events state */
}

/*
** ===================================================================
**     Method      :  flash_DisableEvent (component IntFLASH)
*/
/*!
**     @brief
**         This method disables all the events except [OnSaveBuffer],
**         [OnRestoreBuffer] and [OnEraseError]. The method is
**         available only if any event is enabled.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_SPEED - This device does not work in
**                           the active speed mode
*/
/* ===================================================================*/
byte flash_DisableEvent(void)
{
  flash_EnEvent = FALSE;
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  flash_EnableEvent (component IntFLASH)
*/
/*!
**     @brief
**         This method enables all the events except [OnSaveBuffer],
**         [OnRestoreBuffer] and [OnEraseError]. The method is
**         available only if any event is enabled.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_SPEED - This device does not work in
**                           the active speed mode
*/
/* ===================================================================*/
byte flash_EnableEvent(void)
{
  flash_EnEvent = TRUE;
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  flash_Busy (component IntFLASH)
*/
/*!
**     @brief
**         This method returns the status of the FLASH device. The
**         method may be required and called from another component
**         methods - in this case it cannot be disabled.
**     @param
**         Block           - Number of Flash block. Not used for
**                           Freescale 56800, HCS08, HCS12X and
**                           ColdFireV1 derivates - any value may be
**                           passed.
**     @return
**                         - [true]/[false] - FLASH is busy/ready
*/
/* ===================================================================*/
bool flash_Busy(byte Block)
{
  (void)Block;                         /* Parameter is not used, suppress unused argument warning */
  return flash_CmdPending;
}

/*
** ===================================================================
**     Method      :  flash_EraseSector (component IntFLASH)
*/
/*!
**     @brief
**         Erases the sector to which address Addr belongs.
**     @param
**         Addr            - Address in FLASH.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_NOTAVAIL - Desired program/erase
**                           operation is not available 
**                           - ERR_RANGE - Address is out of range 
**                           - ERR_SPEED - This device does not work in
**                           the active speed mode 
**                           - ERR_BUSY - Device is busy 
**                           - ERR_PROTECT - Flash is write protect 
**                           - ERR_VALUE - Flash sector erase was not
**                           successful
*/
/* ===================================================================*/
byte flash_EraseSector(flash_TAddress Addr)
{
  LDD_TError                 Result;

  if (flash_CmdPending) {
    return ERR_BUSY;
  }
  flash_CurrentCommand = flash_CMD_ERASE_SECTOR;
  flash_CmdPending = TRUE;
  Result = IntFlashLdd1_Erase(IntFlashLdd1_DevDataPtr, (LDD_FLASH_TAddress)Addr, 1U);
  if (Result == ERR_OK) {
    do {
    } while (flash_CmdPending);
    Result = flash_CmdResult;
  } else {
    flash_CmdPending = FALSE;          /* Command parameter error */
    if (Result == ERR_PARAM_ADDRESS) {
      Result = ERR_RANGE;
    }
  }
  return (byte)Result;
}

/*
** ===================================================================
**     Method      :  flash_SetByteFlash (component IntFLASH)
*/
/*!
**     @brief
**         Writes a byte to an address in FLASH. The operation of this
**         method depends on the "Write method" property and state of
**         the flash. Please see more details on general info page of
**         the help.
**     @param
**         Addr            - Address to FLASH.
**     @param
**         Data            - Data to write.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_NOTAVAIL - Desired program/erase
**                           operation is not available 
**                           - ERR_RANGE - Address is out of range 
**                           - ERR_VALUE - Read value is not equal to
**                           written value 
**                           - ERR_SPEED - This device does not work in
**                           the active speed mode 
**                           - ERR_BUSY - Device is busy 
**                           - ERR_PROTECT - Flash is write protect
*/
/* ===================================================================*/
byte flash_SetByteFlash(flash_TAddress Addr, byte Data)
{
  return flash_SetFlash((flash_TDataAddress)(void*)&Data, Addr,1U);
}

/*
** ===================================================================
**     Method      :  flash_SetWordFlash (component IntFLASH)
*/
/*!
**     @brief
**         Writes a word to an address in FLASH. The operation of this
**         method depends on the "Write method" property and state of
**         the flash. Please see more details on general info page of
**         the help.
**     @param
**         Addr            - Address to FLASH.
**     @param
**         Data            - Data to write.
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_NOTAVAIL - Desired program/erase
**                           operation is not available 
**                           - ERR_RANGE - Address is out of range 
**                           - ERR_VALUE - Read value is not equal to
**                           written value 
**                           - ERR_SPEED - This device does not work in
**                           the active speed mode 
**                           - ERR_BUSY - Device is busy 
**                           - ERR_PROTECT - Flash is write protect
*/
/* ===================================================================*/
byte flash_SetWordFlash(flash_TAddress Addr, word Data)
{
  return flash_SetFlash((flash_TDataAddress)(void*)&Data, Addr, 2U);
}

/*
** ===================================================================
**     Method      :  flash_SetBlockFlash (component IntFLASH)
*/
/*!
**     @brief
**         Writes data to FLASH. The operation of this method depends
**         on the "Write method" property and state of the flash.
**         Please see more details on general info page of the help.
**     @param
**         Source          - Source address of the data.
**     @param
**         Dest            - Destination address in FLASH.
**     @param
**         Count           - Count of the data fields (in the
**                           smallest addressable units).
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_NOTAVAIL - Desired program/erase
**                           operation is not available 
**                           - ERR_RANGE - The address is out of range 
**                           - ERR_BUSY - Device is busy 
**                           - ERR_SPEED - This device does not work in
**                           the active speed mode 
**                           - ERR_PROTECT - Flash is write protect 
**                           - ERR_VALUE - Read value is not equal to
**                           written value
*/
/* ===================================================================*/
byte flash_SetBlockFlash(flash_TDataAddress Source, flash_TAddress Dest, word Count)
{
  return flash_SetFlash(Source, Dest, Count);
}

/*
** ===================================================================
**     Method      :  flash_GetBlockFlash (component IntFLASH)
*/
/*!
**     @brief
**         Reads data from FLASH.
**     @param
**         Source          - Destination address in FLASH.
**     @param
**         Dest            - Source address of the data.
**     @param
**         Count           - Count of the data fields (in the
**                           smallest addressable units).
**     @return
**                         - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_NOTAVAIL - Desired program/erase
**                           operation is not available 
**                           - ERR_RANGE - The address is out of range 
**                           - ERR_BUSY - Device is busy
*/
/* ===================================================================*/
byte flash_GetBlockFlash(flash_TAddress Source, flash_TDataAddress Dest, word Count)
{
  LDD_TError                 Result;
  
  if (flash_CmdPending) {
    return ERR_BUSY;
  }
  flash_CurrentCommand = flash_CMD_READ;
  flash_CmdPending = TRUE;
  Result = IntFlashLdd1_Read(IntFlashLdd1_DevDataPtr, (LDD_FLASH_TAddress)Source, (LDD_TData*)Dest, (LDD_FLASH_TDataSize)Count); /* Start reading from the flash memory */
  if (Result == ERR_OK) {              /* Command accepted? */
    do {
      IntFlashLdd1_Main(IntFlashLdd1_DevDataPtr);
    } while (flash_CmdPending);
    Result = flash_CmdResult;
  } else if (Result == ERR_PARAM_ADDRESS) {
    flash_CmdPending = FALSE;
    Result = ERR_RANGE;
  } else {
  }
  return (byte)Result;
}

/*
** ===================================================================
**     Method      :  flash_OnOperationComplete (component IntFLASH)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void IntFlashLdd1_OnOperationComplete(LDD_TUserData *UserDataPtr)
{
  (void)UserDataPtr;                   /* Parameter is not used, suppress unused argument warning */
  flash_CmdResult = ERR_OK;            /* No error appears */
  switch (flash_CurrentCommand) {
    case flash_CMD_WRITE_ERASE:
      flash_CurrentCommand = flash_CMD_WRITE;
      flash_CmdResult = (byte)IntFlashLdd1_Write(IntFlashLdd1_DevDataPtr, flash_DataAddress, flash_FlashAddress, flash_DataSize); /* Start reading from the flash memory */
      if (flash_CmdResult != ERR_OK) { /* Write command error? */
        flash_CmdPending = FALSE;      /* Command is finished */
      }
      return;
    case flash_CMD_WRITE:
      flash_CmdPending = FALSE;        /* Command is finished */
      break;
    default:
      flash_CmdPending = FALSE;        /* Command is finished */
      return;
  }
  if (flash_EnEvent == TRUE) {
    flash_OnWriteEnd();
  }
}

/*
** ===================================================================
**     Method      :  flash_OnError (component IntFLASH)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void IntFlashLdd1_OnError(LDD_TUserData *UserDataPtr)
{
  LDD_FLASH_TErrorStatus FLASH_LDD_ErrorStatus;

  (void)UserDataPtr;                   /* Parameter is not used, suppress unused argument warning */
  flash_CmdPending = FALSE;
  flash_CurrentCommand = flash_CMD_NONE;
  IntFlashLdd1_GetError(IntFlashLdd1_DevDataPtr, &FLASH_LDD_ErrorStatus);
  if (FLASH_LDD_ErrorStatus.CurrentErrorFlags & LDD_FLASH_PROTECTION_VIOLATION) {
    flash_CmdResult = ERR_PROTECT;     /* Protection violation */
  } else {
    flash_CmdResult = ERR_VALUE;       /* Access error or Read collision error */
  }
}

/* END flash. */

#ifdef __cplusplus
}  /* extern "C" */
#endif

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
